blog:
  container_name: blog_web
  image: wordpress:latest
  environment:
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=root
    - WORDPRESS_DB_NAME=blog
  volumes:
    - ./themes:/var/www/html/wp-content/themes
    - ./plugins:/var/www/html/wp-content/plugins
  links:
    - mysql
  ports:
    - "8085:80"

mysql:
    container_name: blog_db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
